/*
* SPDX-FileCopyrightText: 2024 Espressif Systems (Shanghai) CO LTD
*
* SPDX-License-Identifier: Apache-2.0
*/

#pragma once

#include "esp_amp_platform.h"

#ifdef __cplusplus
extern "C" {
#endif

#define ESP_AMP_LOGE  ESP_AMP_PLATFORM_LOGE
#define ESP_AMP_LOGW  ESP_AMP_PLATFORM_LOGW
#define ESP_AMP_LOGI  ESP_AMP_PLATFORM_LOGI
#define ESP_AMP_LOGD  ESP_AMP_PLATFORM_LOGD
#define ESP_AMP_LOGV  ESP_AMP_PLATFORM_LOGV

#define ESP_AMP_DRAM_LOGE ESP_AMP_PLATFORM_DRAM_LOGE
#define ESP_AMP_DRAM_LOGW ESP_AMP_PLATFORM_DRAM_LOGW
#define ESP_AMP_DRAM_LOGI ESP_AMP_PLATFORM_DRAM_LOGI
#define ESP_AMP_DRAM_LOGD ESP_AMP_PLATFORM_DRAM_LOGD
#define ESP_AMP_DRAM_LOGV ESP_AMP_PLATFORM_DRAM_LOGV

#define ESP_AMP_LOG_BUFFER_HEXDUMP ESP_AMP_PLATFORM_LOG_BUFFER_HEXDUMP
#define ESP_AMP_LOG_BUFFER_HEX ESP_AMP_PLATFORM_LOG_BUFFER_HEX

#define ESP_AMP_LOG_ERROR ESP_AMP_PLATFORM_LOG_ERROR
#define ESP_AMP_LOG_WARNING ESP_AMP_PLATFORM_LOG_WARNING
#define ESP_AMP_LOG_INFO ESP_AMP_PLATFORM_LOG_INFO
#define ESP_AMP_LOG_DEBUG ESP_AMP_PLATFORM_LOG_DEBUG
#define ESP_AMP_LOG_VERBOSE ESP_AMP_PLATFORM_LOG_VERBOSE

#ifdef __cplusplus
}
#endif
